import Navbar from "@/components/Navbar";
import React from "react";
import { motion } from "framer-motion";
import Footer from "@/components/Footer";

const index = () => {
	return (
		<>
			<div className="wrapper bg-purple">
				<div className="contain">
					<Navbar />
				</div>
			</div>
			<motion.div
				initial={{ scale: 0.8, opacity: 0 }}
				animate={{ scale: 1, opacity: 1 }}
				exit={{ scale: 0.4, opacity: 0 }}
				transition={{ type: "spring", duration: 1 }}
				className="wrapper text-black">
				<div className="contain my-[30px] flex-col  md:my-[60px]">
					<div>
						<h1 className="subHeadings font-extrabold ">Terms and Condition</h1>
						<p className="des font-medium">Updated at 2022-09-15</p>
					</div>
					<div className="mt-10 flex w-full flex-col gap-10">
						<div className="">
							<h1 className="title font-bold">General Terms</h1>
							<p className="des mt-2">
								By accessing and placing an order with Readrly , you confirm
								that you are in agreement with and bound by the terms of service
								contained in the Terms & Conditions outlined below. These terms
								apply to the entire website and any email or other type of
								communication between you and Readrly . Under no circumstances
								shall Readrly team be liable for any direct, indirect, special,
								incidental or consequential damages, including, but not limited
								to, loss of data or profit, arising out of the use, or the
								inability to use, the materials on this site, even if Readrly
								team or an authorized representative has been advised of the
								possibility of such damages. If your use of materials from this
								site results in the need for servicing, repair or correction of
								equipment or data, you assume any costs thereof. Readrly will
								not be responsible for any outcome that may occur during the
								course of usage of our resources. We reserve the rights to
								change prices and revise the resources usage policy in any
								moment. This Terms & Conditions was created with Termify.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">License</h1>
							<p className="des mt-2">
								Readrly grants you a revocable, non-exclusive, non-transferable,
								limited license to download, install and use the app strictly in
								accordance with the terms of this Agreement. These Terms &
								Conditions are a contract between you and Readrly (referred to
								in these Terms & Conditions as Readrly , we or our), the
								provider of the Readrly website and the services accessible from
								the Readrly website (which are collectively referred to in these
								Terms & Conditions as the Readrly Service. You are agreeing to
								be bound by these Terms & Conditions. If you do not agree to
								these Terms & Conditions, please do not use the Readrly Service.
								In these Terms & Conditions, you refers both to you as an
								individual and to the entity you represent. If you violate any
								of these Terms & Conditions, we reserve the right to cancel your
								account or block access to your account without notice.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Definitions and key terms</h1>
							<p className="des mt-2">
								To help explain things as clearly as possible in this Terms &
								Conditions, every time any of these terms are referenced, are
								strictly defined as:
							</p>
							<ul className="des list-outside list-disc pl-4">
								<li>
									Cookie: small amount of data generated by a website and saved
									by your web browser. It is used to identify your browser,
									provide analytics, remember information about you such as your
									language preference or login information.
								</li>
								<li>
									Company: when this terms mention “Company,” “we,” “us,” or
									“our,” it refers to Readrly , that is responsible for your
									information under this Terms & Conditions.
								</li>
								<li>
									Country: where Readrly or the owners/founders of Readrly are
									based, in this case is United Kingdom
								</li>
								<li>
									Device: any internet connected device such as a phone, tablet,
									computer or any other device that can be used to visit Readrly
									and use the services.
								</li>
								<li>
									Service: refers to the service provided by Readrly as
									described in the relative terms (if available) and on this
									platform.
								</li>
								<li>
									Third-party service: refers to advertisers, contest sponsors,
									promotional and marketing partners, and others who provide our
									content or whose products or services we think may interest
									you.
								</li>
								<li>
									Website: Readrly ’s site, which can be accessed via this URL:
								</li>
								<li>
									You: a person or entity that is registered with Readrly to use
									the Services
								</li>
							</ul>
						</div>
						<div className="">
							<h1 className="title font-bold">Restrictions</h1>
							<p className="des mt-2">
								You agree not to, and you will not permit others to:
							</p>
							<ul className="des list-outside list-disc pl-4">
								<li>
									Modify, make derivative works of, disassemble, decrypt,
									reverse compile or reverse engineer any part of the app.
								</li>
								<li>
									Remove, alter or obscure any proprietary notice (including any
									notice of copyright or trademark) of Readrly or its
									affiliates, partners, suppliers or the licensors of the app.
								</li>
							</ul>
						</div>
						<div className="">
							<h1 className="title font-bold">Payment</h1>
							<p className="des mt-2">
								If you register to any of our recurring payment plans, you agree
								to pay all fees or charges to your account for the Service in
								accordance with the fees, charges and billing terms in effect at
								the time that each fee or charge is due and payable. Unless
								otherwise indicated in an order form, you must provide Readrly
								with a valid credit card (Visa, MasterCard, or any other issuer
								accepted by us) (“Payment Provider”) as a condition to signing
								up for the Premium plan. Your Payment Provider agreement governs
								your use of the designated credit card account, and you must
								refer to that agreement and not these Terms to determine your
								rights and liabilities with respect to your Payment Provider. By
								providing Readrly with your credit card number and associated
								payment information, you agree that Readrly is authorized to
								verify information immediately, and subsequently invoice your
								account for all fees and charges due and payable to Readrly
								hereunder and that no additional notice or consent is required.
								You agree to immediately notify Readrly of any change in your
								billing address or the credit card used for payment hereunder.
								Readrly reserves the right at any time to change its prices and
								billing methods, either immediately upon posting on our Site or
								by e-mail delivery to your organization’s administrator(s). Any
								attorney fees, court costs, or other costs incurred in
								collection of delinquent undisputed amounts shall be the
								responsibility of and paid for by you. No contract will exist
								between you and Readrly for the Service until Readrly accepts
								your order by a confirmatory e-mail, SMS/MMS message, or other
								appropriate means of communication. You are responsible for any
								third-party fees that you may incur when using the Service.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Return and Refund Policy</h1>
							<p className="des mt-2">
								Thanks for shopping at Readrly . We appreciate the fact that you
								like to buy the stuff we build. We also want to make sure you
								have a rewarding experience while you’re exploring, evaluating,
								and purchasing our products. As with any shopping experience,
								there are terms and conditions that apply to transactions at
								Readrly . We’ll be as brief as our attorneys will allow. The
								main thing to remember is that by placing an order or making a
								purchase at Readrly , you agree to the terms along with Readrly
								’s Privacy Policy. If, for any reason, You are not completely
								satisfied with any good or service that we provide, dont
								hesitate to contact us and we will discuss any of the issues you
								are going through with our product.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Your Suggestions</h1>
							<p className="des mt-2">
								Any feedback, comments, ideas, improvements or suggestions
								(collectively, Suggestions) provided by you to Readrly with
								respect to the app shall remain the sole and exclusive property
								of Readrly . Readrly shall be free to use, copy, modify,
								publish, or redistribute the Suggestions for any purpose and in
								any way without any credit or any compensation to you.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Your Consent</h1>
							<p className="des mt-2">
								Weve updated our Terms & Conditions to provide you with complete
								transparency into what is being set when you visit our site and
								how its being used. By using our app, registering an account, or
								making a purchase, you hereby consent to our Terms & Conditions.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Links to Other Websites</h1>
							<p className="des mt-2">
								This Terms & Conditions applies only to the Services. The
								Services may contain links to other websites not operated or
								controlled by Readrly . We are not responsible for the content,
								accuracy or opinions expressed in such websites, and such
								websites are not investigated, monitored or checked for accuracy
								or completeness by us. Please remember that when you use a link
								to go from the Services to another website, our Terms &
								Conditions are no longer in effect. Your browsing and
								interaction on any other website, including those that have a
								link on our platform, is subject to that website’s own rules and
								policies. Such third parties may use their own cookies or other
								methods to collect information about you.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Cookies</h1>
							<p className="des mt-2">
								Readrly uses Cookies to identify the areas of our website that
								you have visited. A Cookie is a small piece of data stored on
								your computer or mobile device by your web browser. We use
								Cookies to enhance the performance and functionality of our app
								but are non-essential to their use. However, without these
								cookies, certain functionality like videos may become
								unavailable or you would be required to enter your login details
								every time you visit the app as we would not be able to remember
								that you had logged in previously. Most web browsers can be set
								to disable the use of Cookies. However, if you disable Cookies,
								you may not be able to access functionality on our website
								correctly or at all. We never place Personally Identifiable
								Information in Cookies.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">
								Changes To Our Terms & conditions
							</h1>
							<p className="des mt-2">
								You acknowledge and agree that Readrly may stop (permanently or
								temporarily) providing the Service (or any features within the
								Service) to you or to users generally at Readrly ’s sole
								discretion, without prior notice to you. You may stop using the
								Service at any time. You do not need to specifically inform
								Readrly when you stop using the Service. You acknowledge and
								agree that if Readrly disables access to your account, you may
								be prevented from accessing the Service, your account details or
								any files or other materials which is contained in your account.
								If we decide to change our Terms & conditions, we will post
								those changes on this page, and/or update the Terms & conditions
								modification date below.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Modifications to Our app</h1>
							<p className="des mt-2">
								Readrly reserves the right to modify, suspend or discontinue,
								temporarily or permanently, the app or any service to which it
								connects, with or without notice and without liability to you.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Updates to Our app</h1>
							<p className="des mt-2">
								Readrly may from time to time provide enhancements or
								improvements to the features/ functionality of the app, which
								may include patches, bug fixes, updates, upgrades and other
								modifications (Updates). Updates may modify or delete certain
								features and/or functionalities of the app. You agree that
								Readrly has no obligation to (i) provide any Updates, or (ii)
								continue to provide or enable any particular features and/or
								functionalities of the app to you. You further agree that all
								Updates will be (i) deemed to constitute an integral part of the
								app, and (ii) subject to the terms and conditions of this
								Agreement.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Third-Party Services</h1>
							<p className="des mt-2">
								We may display, include or make available third-party content
								(including data, information, applications and other products
								services) or provide links to third-party websites or services
								(Third- Party Services). You acknowledge and agree that Readrly
								shall not be responsible for any Third-Party Services, including
								their accuracy, completeness, timeliness, validity, copyright
								compliance, legality, decency, quality or any other aspect
								thereof. Readrly does not assume and shall not have any
								liability or responsibility to you or any other person or entity
								for any Third-Party Services. Third-Party Services and links
								thereto are provided solely as a convenience to you and you
								access and use them entirely at your own risk and subject to
								such third parties terms and conditions.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Term and Termination</h1>
							<p className="des mt-2">
								This Agreement shall remain in effect until terminated by you or
								Readrly . Readrly may, in its sole discretion, at any time and
								for any or no reason, suspend or terminate this Agreement with
								or without prior notice. This Agreement will terminate
								immediately, without prior notice from Readrly , in the event
								that you fail to comply with any provision of this Agreement.
								You may also terminate this Agreement by deleting the app and
								all copies thereof from your computer. Upon termination of this
								Agreement, you shall cease all use of the app and delete all
								copies of the app from your computer. Termination of this
								Agreement will not limit any of Readrly s rights or remedies at
								law or in equity in case of breach by you (during the term of
								this Agreement) of any of your obligations under the present
								Agreement.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Copyright Infringement Notice</h1>
							<p className="des mt-2">
								If you are a copyright owner or such owners agent and believe
								any material on our app constitutes an infringement on your
								copyright, please contact us setting forth the following
								information: (a) a physical or electronic signature of the
								copyright owner or a person authorized to act on his behalf; (b)
								identification of the material that is claimed to be infringing;
								(c) your contact information, including your address, telephone
								number, and an email; (d) a statement by you that you have a
								good faith belief that use of the material is not authorized by
								the copyright owners; and (e) the a statement that the
								information in the notification is accurate, and, under penalty
								of perjury you are authorized to act on behalf of the owner.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Indemnification</h1>
							<p className="des mt-2">
								You agree to indemnify and hold Readrly and its parents,
								subsidiaries, affiliates, officers, employees, agents, partners
								and licensors (if any) harmless from any claim or demand,
								including reasonable attorneys fees, due to or arising out of
								your: (a) use of the app; (b) violation of this Agreement or any
								law or regulation; or (c) violation of any right of a third
								party.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">No Warranties</h1>
							<p className="des mt-2">
								The app is provided to you AS IS and AS AVAILABLE and with all
								faults and defects without warranty of any kind. To the maximum
								extent permitted under applicable law, Readrly , on its own
								behalf and on behalf of its affiliates and its and their
								respective licensors and service providers, expressly disclaims
								all warranties, whether express, implied, statutory or
								otherwise, with respect to the app, including all implied
								warranties of merchantability, fitness for a particular purpose,
								title and non-infringement, and warranties that may arise out of
								course of dealing, course of performance, usage or trade
								practice. Without limitation to the foregoing, Readrly provides
								no warranty or undertaking, and makes no representation of any
								kind that the app will meet your requirements, achieve any
								intended results, be compatible or work with any other software,
								apps, systems or services, operate without interruption, meet
								any performance or reliability standards or be error free or
								that any errors or defects can or will be corrected. Without
								limiting the foregoing, neither Readrly nor any Readrly s
								provider makes any representation or warranty of any kind,
								express or implied: (i) as to the operation or availability of
								the app, or the information, content, and materials or products
								included thereon; (ii) that the app will be uninterrupted or
								error-free; (iii) as to the accuracy, reliability, or currency
								of any information or content provided through the app; or (iv)
								that the app, its servers, the content, or e-mails sent from or
								on behalf of Readrly are free of viruses, scripts, trojan
								horses, worms, malware, timebombs or other harmful components.
								Some jurisdictions do not allow the exclusion of or limitations
								on implied warranties or the limitations on the applicable
								statutory rights of a consumer, so some or all of the above
								exclusions and limitations may not apply to you.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Limitation of Liability</h1>
							<p className="des mt-2">
								Notwithstanding any damages that you might incur, the entire
								liability of Readrly and any of its suppliers under any
								provision of this Agreement and your exclusive remedy for all of
								the foregoing shall be limited to the amount actually paid by
								you for the app. To the maximum extent permitted by applicable
								law, in no event shall Readrly or its suppliers be liable for
								any special, incidental, indirect, or consequential damages
								whatsoever (including, but not limited to, damages for loss of
								profits, for loss of data or other information, for business
								interruption, for personal injury, for loss of privacy arising
								out of or in any way related to the use of or inability to use
								the app, third-party software and/or third-party hardware used
								with the app, or otherwise in connection with any provision of
								this Agreement), even if Readrly or any supplier has been
								advised of the possibility of such damages and even if the
								remedy fails of its essential purpose. Some states/jurisdictions
								do not allow the exclusion or limitation of incidental or
								consequential damages, so the above limitation or exclusion may
								not apply to you.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Severability</h1>
							<p className="des mt-2">
								If any provision of this Agreement is held to be unenforceable
								or invalid, such provision will be changed and interpreted to
								accomplish the objectives of such provision to the greatest
								extent possible under applicable law and the remaining
								provisions will continue in full force and effect. This
								Agreement, together with the Privacy Policy and any other legal
								notices published by Readrly on the Services, shall constitute
								the entire agreement between you and Readrly concerning the
								Services. If any provision of this Agreement is deemed invalid
								by a court of competent jurisdiction, the invalidity of such
								provision shall not affect the validity of the remaining
								provisions of this Agreement, which shall remain in full force
								and effect. No waiver of any term of this Agreement shall be
								deemed a further or continuing waiver of such term or any other
								term, and Readrly ’s failure to assert any right or provision
								under this Agreement shall not constitute a waiver of such right
								or provision. YOU AND Readrly AGREE THAT ANY CAUSE OF ACTION
								ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN
								ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH
								CAUSE OF ACTION IS PERMANENTLY BARRED.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Waiver</h1>
							<p className="des mt-2">
								Except as provided herein, the failure to exercise a right or to
								require performance of an obligation under this Agreement shall
								not effect a partys ability to exercise such right or require
								such performance at any time thereafter nor shall be the waiver
								of a breach constitute waiver of any subsequent breach. No
								failure to exercise, and no delay in exercising, on the part of
								either party, any right or any power under this Agreement shall
								operate as a waiver of that right or power. Nor shall any single
								or partial exercise of any right or power under this Agreement
								preclude further exercise of that or any other right granted
								herein. In the event of a conflict between this Agreement and
								any applicable purchase or other terms, the terms of this
								Agreement shall govern.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Amendments to this Agreement</h1>
							<p className="des mt-2">
								Readrly reserves the right, at its sole discretion, to modify or
								replace this Agreement at any time. If a revision is material we
								will provide at least 30 days notice prior to any new terms
								taking effect. What constitutes a material change will be
								determined at our sole discretion. By continuing to access or
								use our app after any revisions become effective, you agree to
								be bound by the revised terms. If you do not agree to the new
								terms, you are no longer authorized to use Readrly .
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Entire Agreement</h1>
							<p className="des mt-2">
								The Agreement constitutes the entire agreement between you and
								Readrly regarding your use of the app and supersedes all prior
								and contemporaneous written or oral agreements between you and
								Readrly . You may be subject to additional terms and conditions
								that apply when you use or purchase other Readrlys services,
								which Readrly will provide to you at the time of such use or
								purchase.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Updates to Our Terms</h1>
							<p className="des mt-2">
								We may change our Service and policies, and we may need to make
								changes to these Terms so that they accurately reflect our
								Service and policies. Unless otherwise required by law, we will
								notify you (for example, through our Service) before we make
								changes to these Terms and give you an opportunity to review
								them before they go into effect. Then, if you continue to use
								the Service, you will be bound by the updated Terms. If you do
								not want to agree to these or any updated Terms, you can delete
								your account.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Miscellaneous</h1>
							<p className="des mt-2">
								If for any reason a court of competent jurisdiction finds any
								provision or portion of these Terms & Conditions to be
								unenforceable, the remainder of these Terms & Conditions will
								continue in full force and effect. Any waiver of any provision
								of these Terms & Conditions will be effective only if in writing
								and signed by an authorized representative of Readrly . Readrly
								will be entitled to injunctive or other equitable relief
								(without the obligations of posting any bond or surety) in the
								event of any breach or anticipatory breach by you. Readrly
								operates and controls the Readrly Service from its offices in
								United Kingdom. The Service is not intended for distribution to
								or use by any person or entity in any jurisdiction or country
								where such distribution or use would be contrary to law or
								regulation. Accordingly, those persons who choose to access the
								Readrly Service from other locations do so on their own
								initiative and are solely responsible for compliance with local
								laws, if and to the extent local laws are applicable. These
								Terms & Conditions (which include and incorporate the Readrly
								Privacy Policy) contains the entire understanding, and
								supersedes all prior understandings, between you and Readrly
								concerning its subject matter, and cannot be changed or modified
								by you. The section headings used in this Agreement are for
								convenience only and will not be given any legal import.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Disclaimer</h1>
							<p className="des mt-2">
								Readrly is not responsible for any content, code or any other
								imprecision. Readrly does not provide warranties or guarantees.
								In no event shall Readrly be liable for any special, direct,
								indirect, consequential, or incidental damages or any damages
								whatsoever, whether in an action of contract, negligence or
								other tort, arising out of or in connection with the use of the
								Service or the contents of the Service. The Company reserves the
								right to make additions, deletions, or modifications to the
								contents on the Service at any time without prior notice. The
								Readrly Service and its contents are provided without any
								warranty or representations of any kind, whether express or
								implied. Readrly is a distributor and not a publisher of the
								content supplied by third parties; as such, Readrly exercises no
								editorial control over such content and makes no warranty or
								representation as to the accuracy, reliability or currency of
								any information, content, service or merchandise provided
								through or accessible via the Readrly Service. Without limiting
								the foregoing, Readrly specifically disclaims all warranties and
								representations in any content transmitted on or in connection
								with the Readrly Service or on sites that may appear as links on
								the Readrly Service, or in the products provided as a part of,
								or otherwise in connection with, the Readrly Service, including
								without limitation any warranties of merchantability, fitness
								for a particular purpose or non-infringement of third party
								rights. No oral advice or written information given by Readrly
								or any of its affiliates, employees, officers, directors,
								agents, or the like will create a warranty. Price and
								availability information is subject to change without notice.
								Without limiting the foregoing, Readrly does not warrant that
								the Readrly Service will be uninterrupted, uncorrupted, timely,
								or error-free.
							</p>
						</div>
						<div className="">
							<h1 className="title font-bold">Contact Us</h1>
							<p className="des mt-2">
								Dont hesitate to contact us if you have any questions.
							</p>
							<ul className="des list-outside list-disc pl-3">
								<li className="cursor-pointer">Via Email: info@readrly.io</li>
								<li className="cursor-pointer">
									Via this Link: https://www.readrly.io/
								</li>
							</ul>
							<p className="des cursor-pointer">
								Contact <br /> Info@readrly.io
							</p>
						</div>
					</div>
				</div>
			</motion.div>

			<div className="wrapper">
				<Footer />
			</div>
		</>
	);
};

export default index;
