/* eslint-disable @next/next/no-img-element */
import Layout from "@/Layout/Layout";
import Head from "next/head";
import { useEffect, useState } from "react";
import ClipLoader from "react-spinners/ClipLoader";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="w-full">
				<Layout />
			</div>
		</>
	);
}
